const products = [
    {
        '_id': '1',
        'name': 'Airpods Wireless Bluetooth Headphones',
        'image': '/images/airpods.jpg',
        'description': 'Airpods Wireless Bluetooth Headphones',
        'brand': 'Apple',
        'category': 'Electronics',
        'price': 89.99,
        'countInStock': 10,
        'rating': 4.99,
        'numReviews': 12,
    },

    {
        '_id': '2',
        'name': 'iphone 11 Pro 256GB Memory',
        'image': '/images/phone.jpg',
        'description': 'Introduction the iphone 11 Pro 256GB Memory',
        'brand': 'Apple',
        'category': 'Electronics',
        'price': 599.99,
        'countInStock': 7,
        'rating': 4.0,
        'numReviews': 8,
    },

    {
        '_id': '3',
        'name': 'Cannon EOS 80D DSLR Camera',
        'image': '/images/camera.jpg',
        'description': 'Introduction the  Cannon EOS 80D DSLR Camera',
        'brand': 'Cannon',
        'category': 'Electronics',
        'price': 399.99,
        'countInStock': 17,
        'rating': 3.0,
        'numReviews': 7,
    },

    {
        '_id': '4',
        'name': 'Sony Playstation 4 Pro White Version',
        'image': '/images/playstation.jpg',
        'description': 'Introduction the  Sony Playstation',
        'brand': 'Sony',
        'category': 'Electronics',
        'price': 399.99,
        'countInStock': 11,
        'rating': 3.0,
        'numReviews': 12,
    },

    {
        '_id': '5',
        'name': 'Logitech G-Series Gaming Mouse',
        'image': '/images/mouse.jpg',
        'description': 'Introduction the  Logitech G-Series',
        'brand': 'Logitech',
        'category': 'Electronics',
        'price': 49.99,
        'countInStock': 7,
        'rating': 3.5,
        'numReviews': 10,
    },
    
    {
        '_id': '6',
        'name': 'Amazon Echo Dot 3rd Generation',
        'image': '/images/alexa.jpg',
        'description': 'Introduction the  Amazon Echo Dot 3rd Generation',
        'brand': 'Amazon',
        'category': 'Electronics',
        'price': 399.99,
        'countInStock': 17,
        'rating': 3.0,
        'numReviews': 12,
    },
]

export default products